UPDATE docs SET body=json_set(body,'$.real_sanitized_receipts[0].candidate_sha256',printf('%064d',0)) WHERE id='u29o1';
UPDATE docs SET body=json_set(body,'$.real_sanitized_receipts[0].schema_candidate',7) WHERE id='u29o1';
UPDATE docs SET body=json_set(body,'$.real_sanitized_receipts[0].schema_before',8) WHERE id='u29o1';
UPDATE docs SET body=json_set(body,'$.real_sanitized_receipts[0].schema_restored',8) WHERE id='u29o1';
UPDATE docs SET body=json_set(body,'$.real_sanitized_receipts[0].synthetic_only',json('true')) WHERE id='u29o1';
UPDATE docs SET body=json_set(body,'$.real_sanitized_receipts[0].evidence_kind','synthetic_fixture') WHERE id='u29o1';
UPDATE docs SET body=json_set(body,'$.real_sanitized_receipts[0].old_run_advanced_on_candidate',json('false')) WHERE id='u29o1';
UPDATE docs SET body=json_set(body,'$.real_sanitized_receipts[0].restored_old_runtime_advanced',json('false')) WHERE id='u29o1';
UPDATE docs SET body=json_set(body,'$.real_sanitized_receipts[0].baseline_mode_preparation_content_unchanged',json('false')) WHERE id='u29o1';
UPDATE docs SET body=json_set(body,'$.real_sanitized_receipts[0].original_bytes_modes_exact_before_baseline_preparation',json('false')) WHERE id='u29o1';
UPDATE docs SET body=json_set(body,'$.real_sanitized_receipts[0].unprepared_baseline_continuation_claimed',json('true')) WHERE id='u29o1';
UPDATE docs SET body=json_set(body,'$.real_sanitized_receipts[0].rollback_validation_mode','original_modes') WHERE id='u29o1';
UPDATE docs SET body=json_set(body,'$.real_sanitized_receipts[0].release_qualified',json('true')) WHERE id='u29o1';
UPDATE docs SET body=json_set(body,'$.real_sanitized_receipts[0].copied_operator_state_gate_passed',json('true')) WHERE id='u29o1';
UPDATE docs SET body=json_set(body,'$.real_sanitized_receipts[0].production_modified',json('true')) WHERE id='u29o1';
UPDATE docs SET body=json_set(body,'$.real_sanitized_receipts[0].schema_candidate',8.0) WHERE id='u29o1';
UPDATE docs SET body=json_remove(body,'$.real_sanitized_receipts[0].candidate_sha256') WHERE id='u29o1';
UPDATE docs SET body=json_set(body,'$.real_sanitized_receipts[0].new_authority',json('true')) WHERE id='u29o1';
UPDATE docs SET body=json_set(body,'$.real_sanitized_receipts[0].candidate_sha256',NULL) WHERE id='u29o1';
UPDATE docs SET body=replace(body,'"schema_candidate": 8','"schema_candidate":8,"schema_candidate":8') WHERE id='u29o1';
UPDATE docs SET body=replace(body,'"schema_candidate": 8','"schema_candidate":8,"\u0073chema_candidate":8') WHERE id='u29o1';
UPDATE docs SET body=json_set(body,'$.real_sanitized_receipts',json('[]')) WHERE id='u29o1';
UPDATE docs SET body=json_set(body,'$.working_session_identity_sha256',json_extract((SELECT body FROM docs WHERE id='u29o1'),'$.working_session_identity_sha256')) WHERE id='u29o2';
UPDATE docs SET body=json_set(body,'$.command_id',json_extract((SELECT body FROM docs WHERE id='u29o1'),'$.command_id')) WHERE id='u29o2';
UPDATE docs SET body=json_set(body,'$.working_copy_identity_sha256',json_extract((SELECT body FROM docs WHERE id='u29p1'),'$.working_copy_identity_sha256')) WHERE id='u29p2';
UPDATE docs SET body=json_set(body,'$.finished_at','2026-09-30T10:00:00.000000+00:00') WHERE id='u29o1';
UPDATE docs SET body=json_set(body,'$.started_at','2026-09-30T99:00:00.000000+00:00') WHERE id='u29o1';
UPDATE docs SET body=json_set(body,'$.baseline_exact_restoration_proof_sha256',printf('%064d',0)) WHERE id='u29o1';
UPDATE docs SET body=json_set(body,'$.before_baseline_mode_preparation',json('false')) WHERE id='u29p1';
UPDATE docs SET body=json_set(body,'$.prepared_modes_used_for_exact_check',json('true')) WHERE id='u29p1';
UPDATE docs SET body=json_set(body,'$.archive_sha256',printf('%064d',0)) WHERE id='u29p1';
UPDATE docs SET body=json_set(body,'$.rows[0]',json_extract(body,'$.rows[1]')) WHERE id='base';
UPDATE docs SET body=json_set(body,'$.rows[78].status','accepted') WHERE id='base';
UPDATE docs SET body=json_remove(body,'$.rows[0]') WHERE id='base';
UPDATE docs SET body=json_set(body,'$.rows[0].task_id','U26') WHERE id='authority_proposal';
UPDATE docs SET body=json_set(body,'$.accepted_delta',6) WHERE id='authority_proposal';
UPDATE docs SET body=json_set(body,'$.rows[1]',json_extract(body,'$.rows[0]')) WHERE id='authority_proposal';
UPDATE docs SET body=json_set(body,'$.passed',json('false')) WHERE id='source_gate';
UPDATE docs SET body=json_set(body,'$.source_identity.before_sha256',printf('%064d',0)) WHERE id='source_gate';
UPDATE docs SET body=json_set(body,'$.root_cause','fixed') WHERE id='regression';
UPDATE docs SET body=json_set(body,'$.source_capture_repeated',json('true')) WHERE id='u29_aggregate';
UPDATE docs SET body=json_set(body,'$.original_modes_baseline_continuation',json('true')) WHERE id='u29_aggregate';
UPDATE docs SET body=json_set(body,'$.same_original_old_run_preserved',json('false')) WHERE id='u29_aggregate';
UPDATE docs SET body=json_set(body,'$.strict_failure_still_failed',json('false')) WHERE id='u29_review';
UPDATE docs SET body=json_set(body,'$.u29_import_input_review_passed',json('false')) WHERE id='u29_review';
DELETE FROM docs WHERE id='u29o3';
UPDATE docs SET body=json_set(body,'$.accepted_delta',9) WHERE id='input';
UPDATE docs SET body=json_set(body,'$.refs.u29o1.path','../outside.json') WHERE id='input';
UPDATE docs SET body=json_set(body,'$.refs.u29o1.extra','unknown') WHERE id='input';
UPDATE docs SET body=json_set(body,'$.archive_sha256',NULL) WHERE id='u29o1';
UPDATE docs SET body=json_set(body,'$.real_attempt_sequence',NULL) WHERE id='u29o1';
UPDATE docs SET body=json_set(body,'$.working_session_identity_sha256',123) WHERE id='u29o1';
UPDATE docs SET body=json_set(body,'$.repetitions[1]',json_extract(body,'$.repetitions[0]')) WHERE id='u29_aggregate';
UPDATE docs SET body=json_set(body,'$.proc_visibility_complete',json('true')) WHERE id='capture';
UPDATE docs SET body=json_set(body,'$.transactional_snapshot_claimed',json('true')) WHERE id='capture';
UPDATE docs SET body=json_set(body,'$.source_authorized',json('false')) WHERE id='capture';
UPDATE docs SET body=json_set(body,'$.repetitions[1]',json_extract(body,'$.repetitions[0]'),'$.repetitions[2]',json_extract(body,'$.repetitions[0]')) WHERE id='u29_aggregate';
UPDATE docs SET body=json_set(body,'$.helper_sha256',1) WHERE id='u29o1';
UPDATE docs SET body=json_set(body,'$.working_copy_identity_sha256',NULL) WHERE id='u29p1';
UPDATE docs SET body=json_set(body,'$.archive_sha256','not-a-digest') WHERE id='u29_aggregate';
UPDATE context SET testing=0;
UPDATE docs SET body=json_set(body,'$.candidate_sha256',printf('%064d',0)) WHERE id='base';
UPDATE docs SET body=json_set(body,'$.candidate_sha256',printf('%064d',0)) WHERE id='authority_proposal';
UPDATE docs SET body=json_set(body,'$.checks[1].name',json_extract(body,'$.checks[0].name')) WHERE id='source_gate';
UPDATE docs SET body=json_set(body,'$.newly_accepted_nonresearch_trials',69) WHERE id='base';
