from __future__ import annotations

import base64
from pathlib import Path
from typing import Any


NOW_ISO = "2026-09-01T02:40:00.000Z"
UNIX_SECONDS = 1_788_252_800
SECRET = b"s" * 32

GENERATOR_PERMISSIONS = [
    "read:problem",
    "read:references",
    "read:project:verified_dependencies",
    "read:steering",
    "read:memory:generation:*",
    "write:memory:generation:*",
    "search:memory:generation:*",
    "retrieve:external:theorems",
    "retrieve:external:research",
    "commit:workflow",
]


def request(database: Path) -> dict[str, Any]:
    return {
        "database": str(database),
        "now_iso": NOW_ISO,
        "unix_seconds": UNIX_SECONDS,
        "hex_ids": [
            "1111111111111111",
            "2222222222222222",
            "3333333333333333",
        ],
        "urlsafe_ids": [
            "nonce-fixed-000000000001",
            "nonce-fixed-000000000002",
            "nonce-fixed-000000000003",
        ],
        "secret_base64": base64.b64encode(SECRET).decode("ascii"),
        "operations": operations(),
    }


def op(name: str, **args: Any) -> dict[str, Any]:
    return {"op": name, "args": args}


def operations() -> list[dict[str, Any]]:
    return [
        op("schema_version"),
        op(
            "create_run",
            run_id="run-main",
            problem_id="problem-main",
            owner_id="owner",
            state="assess",
            metadata={"workflow_protocol_version": 2, "native_mode_at_creation": "dangerous"},
        ),
        op(
            "create_run",
            run_id="run-main",
            problem_id="duplicate",
            owner_id="owner",
            state="assess",
            metadata={},
        ),
        op(
            "create_domain",
            domain_id="domain-assess",
            run_id="run-main",
            role="generator",
            snapshot_id=None,
            order_index=None,
            metadata={},
        ),
        op(
            "capability_issue",
            run_id="run-main",
            domain_id="domain-assess",
            role="generator",
            permissions=GENERATOR_PERMISSIONS,
            trace_id="trace-cap-1",
            ttl_seconds=600,
        ),
        op(
            "capability_validate_last",
            owner_id="owner",
            action="read",
            resource="problem",
            trace_id="trace-cap-valid-1",
            expected_run_id="run-main",
        ),
        op(
            "update_run_metadata",
            run_id="run-main",
            updates={"effective_workflow_mode": "full", "note": "updated"},
        ),
        op(
            "transition_run",
            run_id="run-main",
            expected_state="assess",
            after_state="explore",
            trace_id="trace-transition-1",
            actor="generator",
            reason="assessment_complete",
            evidence={"route": "full"},
            increment_epoch=True,
            status="active",
            latex_passed=False,
            verdict=None,
            sealed=False,
            round_delta=1,
        ),
        op(
            "capability_validate_last",
            owner_id="owner",
            action="read",
            resource="problem",
            trace_id="trace-cap-revoked-1",
            expected_run_id="run-main",
        ),
        op(
            "transition_run",
            run_id="run-main",
            expected_state="assess",
            after_state="explore",
            trace_id="trace-transition-conflict",
            actor="generator",
            reason="stale",
            evidence={},
            increment_epoch=True,
            round_delta=0,
        ),
        op(
            "create_domain",
            domain_id="domain-explore",
            run_id="run-main",
            role="generator",
            snapshot_id=None,
            order_index=1,
            metadata={},
        ),
        op(
            "capability_issue",
            run_id="run-main",
            domain_id="domain-explore",
            role="generator",
            permissions=GENERATOR_PERMISSIONS,
            trace_id="trace-cap-2",
            ttl_seconds=600,
        ),
        op(
            "capability_validate_last",
            owner_id="owner",
            action="read",
            resource="memory:generation:events",
            trace_id="trace-cap-valid-2",
            expected_run_id="run-main",
        ),
        op("capability_revoke_last", reason="operator_revoke", trace_id="trace-cap-revoke-2"),
        op(
            "capability_validate_last",
            owner_id="owner",
            action="read",
            resource="problem",
            trace_id="trace-cap-revoked-2",
            expected_run_id="run-main",
        ),
        op(
            "capability_issue",
            run_id="run-main",
            domain_id="domain-explore",
            role="generator",
            permissions=GENERATOR_PERMISSIONS,
            trace_id="trace-cap-3",
            ttl_seconds=600,
        ),
        op(
            "tamper_capability_permissions",
            nonce="nonce-fixed-000000000003",
            permissions=["read:problem"],
        ),
        op(
            "capability_validate_last",
            owner_id="owner",
            action="read",
            resource="problem",
            trace_id="trace-cap-tampered",
            expected_run_id="run-main",
        ),
        op(
            "create_branch",
            branch_id="branch-a",
            run_id="run-main",
            plan_id="plan-a",
            domain_id="domain-explore",
            snapshot_id="snapshot-a",
            order_index=0,
            metadata={"route": "a"},
        ),
        op(
            "update_branch_status",
            branch_id="branch-a",
            status="sealed",
            result_path="branches/a.json",
        ),
        op("list_branches", run_id="run-main"),
        op("add_steering", run_id="run-main", owner_id="owner", message="continue"),
        op("consume_steering", run_id="run-main", limit=20),
        op("consume_steering", run_id="run-main", limit=20),
        op("list_transitions", run_id="run-main"),
        op(
            "create_project",
            owner_id="owner",
            title="Project",
            project_id="project-main",
            metadata={"topic": "test"},
        ),
        op("get_project", project_id="project-main", owner_id="other-owner"),
        op(
            "create_claim",
            owner_id="owner",
            project_id="project-main",
            title="Main claim",
            claim_id="claim-main",
            metadata={},
        ),
        op(
            "create_open_claim_revision",
            owner_id="owner",
            claim_id="claim-main",
            statement_tex="$1=1$.",
            conditions=[],
            expected_base_revision_id=None,
        ),
        op(
            "create_claim",
            owner_id="owner",
            project_id="project-main",
            title="Dependency claim",
            claim_id="claim-dependency",
            metadata={},
        ),
        op(
            "create_open_claim_revision",
            owner_id="owner",
            claim_id="claim-dependency",
            statement_tex="$2=2$.",
            conditions=["base condition"],
            expected_base_revision_id=None,
        ),
        op("create_project_snapshot", project_id="project-main", owner_id="owner"),
        op(
            "create_run",
            run_id="run-promote",
            problem_id="promotion",
            owner_id="owner",
            state="done",
            metadata={"workflow_protocol_version": 2},
        ),
        op(
            "create_run",
            run_id="run-conflict",
            problem_id="promotion-conflict",
            owner_id="owner",
            state="done",
            metadata={"workflow_protocol_version": 2},
        ),
        op(
            "link_run_to_project",
            run_id="run-promote",
            owner_id="owner",
            project_id="project-main",
            project_snapshot_id="ps-1111111111111111",
            target_claim_id="claim-main",
            base_revision_id="claim-main-r1",
            requested_workflow_mode="compact",
            effective_workflow_mode="compact",
            register_result=True,
        ),
        op(
            "link_run_to_project",
            run_id="run-conflict",
            owner_id="owner",
            project_id="project-main",
            project_snapshot_id="ps-1111111111111111",
            target_claim_id="claim-main",
            base_revision_id="claim-main-r1",
            requested_workflow_mode="full",
            effective_workflow_mode="full",
            register_result=True,
        ),
        op(
            "write_proof_manifest",
            run_id="run-promote",
            manifest={"dependency_revision_ids": ["claim-dependency-r1"], "target": "claim-main"},
        ),
        op(
            "register_reference",
            run_id="run-promote",
            project_id="project-main",
            provider="paper",
            identity_key="doi:10.1/example",
            title="Example",
            paper_id="paper-1",
            arxiv_id="",
            doi="10.1/example",
            theorem_id="Thm 1",
            source_uri="https://example.invalid/paper",
            source_state="candidate",
            source_sha256="",
            content_sha256="",
            metadata={"year": 2026},
        ),
        op(
            "register_reference",
            run_id="run-promote",
            project_id="project-main",
            provider="paper",
            identity_key="doi:10.1/example",
            title="Ignored duplicate",
            paper_id="paper-2",
            arxiv_id="",
            doi="10.1/example",
            theorem_id="",
            source_uri="",
            source_state="candidate",
            source_sha256="",
            content_sha256="",
            metadata={},
        ),
        op(
            "create_source_snapshot",
            reference_id="ref-2222222222222222",
            provider="paper",
            source_uri="https://example.invalid/paper",
            content="source text",
            content_type="text/plain",
            metadata={"page": 1},
        ),
        op(
            "write_reference_audit",
            run_id="run-promote",
            reference_id="ref-2222222222222222",
            disposition="SOURCE_VERIFIED",
            evidence_basis="source",
            evidence_locator="page 1",
            verifier_domain_id="domain-verifier",
            proof_sha256="a" * 64,
            proof_manifest_sha256="b" * 64,
            material=True,
            assumptions_checked=True,
            notation_checked=True,
            source_checked=True,
            independently_rederived=False,
            notes="checked",
        ),
        op(
            "promote_verified_run",
            run_id="run-promote",
            owner_id="owner",
            statement_tex="$1=1$.",
            proof_sha256="c" * 64,
            effective_conditions=[],
            manifest={"dependency_revision_ids": ["missing-revision"]},
        ),
        op("get_project_run", run_id="run-promote", owner_id="owner"),
        op("list_claim_revisions", claim_id="claim-main", owner_id="owner"),
        op(
            "promote_verified_run",
            run_id="run-promote",
            owner_id="owner",
            statement_tex="$1=1$.",
            proof_sha256="c" * 64,
            effective_conditions=["condition b", "condition a", "condition b"],
            manifest={"dependency_revision_ids": ["claim-dependency-r1"]},
        ),
        op(
            "promote_verified_run",
            run_id="run-promote",
            owner_id="owner",
            statement_tex="$1=1$.",
            proof_sha256="c" * 64,
            effective_conditions=[],
            manifest={"dependency_revision_ids": []},
        ),
        op(
            "promote_verified_run",
            run_id="run-conflict",
            owner_id="owner",
            statement_tex="$1=1$.",
            proof_sha256="d" * 64,
            effective_conditions=[],
            manifest={"dependency_revision_ids": []},
        ),
        op("project_dependency_graph", project_id="project-main", owner_id="owner"),
        op("list_run_references", run_id="run-promote"),
        op("list_source_snapshots", reference_id="ref-2222222222222222"),
        op("list_reference_audits", run_id="run-promote"),
        op("database_snapshot"),
    ]
