[package]
name = "mtm-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "mtm"
path = "src/main.rs"

[dependencies]
mtm-contracts = { version = "=0.4.0-preview.1", path = "../mtm-contracts" }
mtm-runtime = { version = "=0.4.0-preview.1", path = "../mtm-runtime" }
serde_json.workspace = true

[lints]
workspace = true
