[package]
name = "mtm-workflow"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
mtm-contracts = { version = "=0.4.0", path = "../mtm-contracts" }
mtm-core = { version = "=0.4.0", path = "../mtm-core" }
mtm-storage = { version = "=0.4.0", path = "../mtm-storage" }
regex.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
